# id3lib 3.8.3 with consolidated_patches from
# http://www.linuxfromscratch.org/patches/blfs/svn/id3lib-3.8.3-consolidated_patches-1.patch
#
# author: "Finnian Reilly"
# copyright: "Copyright (c) 2001-2010 Finnian Reilly"
# contact: "finnian at eiffel hyphen loop dot com"
# license: "MIT license (See: en.wikipedia.org/wiki/MIT_License)"
# date: "30 Apr 2020"
# revision: "0.1"

import os, sys, platform

from os import path

from eiffel_loop import platform

from eiffel_loop.scons import c_library
from eiffel_loop.scons import util

from eiffel_loop.eiffel import ise_environ

from eiffel_loop.distutils import file_util
from eiffel_loop.package import TAR_GZ_SOFTWARE_PACKAGE

global ise
ise = ise_environ.shared

Import ('env')

env = Environment (
	ENV = os.environ, # this is needed to reproduce the environment for external commands like LIB
	EIFFEL_LOOP = os.environ ['EIFFEL_LOOP'], ISE_PLATFORM = ise.platform
)

if platform.is_unix ():
	build_dir =  ise.spec_build_dir ()
	VariantDir (build_dir, 'source', duplicate=0)

	env ['BUILDERS']['C_library'] = Builder (
		action = c_library.build, suffix='.a', src_suffix='.getlib', emitter = util.complete_targets
	)
	lib = env.C_library (path.join (build_dir, 'libid3.a'), File (path.join (build_dir, 'id3.getlib')))
	
	env.NoClean (lib)
	Return ('lib')
