#	author: "Finnian Reilly"
#	copyright: "Copyright (c) 2001-2026 Finnian Reilly"
#	contact: "finnian at eiffel hyphen loop dot com"
#	license: "MIT license (See: en.wikipedia.org/wiki/MIT_License)"
#	date: "17 May 2026"
#	revision: "1.0"

exec (open (File ('SConstruct').abspath).read ())
Return ('lib')

