# Partial port of build process to Scons
#
#	author: "Finnian Reilly"
#	copyright: "Copyright (c) 2001-2009 Finnian Reilly"
#	contact: "finnian at eiffel hyphen loop dot com"
#	license: "MIT license (See: en.wikipedia.org/wiki/MIT_License)"
#	date: "19 May 2026"
#	revision: "0.2"

import os
from os import path
from eiffel_loop.os import path as el_path
from eiffel_loop.eiffel import ise_environ
from eiffel_loop.C_util import C_dev as C
from eiffel_loop.scons import c

global ise
ise = ise_environ.shared

if os.name == "nt":
	defines = C.define_list ("_LIB COMPILED_FROM_DSP NDEBUG XML_STATIC")
	compiler_flags = ['-nologo', '-W1', '-c', '-MT', '-Ox'] + defines
else:
	defines = C.define_list ("_LIB HAVE_EXPAT_CONFIG_H NDEBUG XML_STATIC")
	compiler_flags = ['-c', '-O3', '-w', '-Wno-write-strings', '-std=gnu99'] + defines

env = Environment (CCFLAGS = compiler_flags, CPPPATH = ['include'], ENV = os.environ)

# Abbreviate long paths in compiler output
c.COMMAND_STRINGS ('C_EXPAT').configure (env)

build_dir = ise.spec_build_dir ()

VariantDir (build_dir, 'source', duplicate=0)

source_list = [path.join (build_dir, name) for name in ['xmlparse.c', 'xmlrole.c', 'xmltok.c']]

lib = env.StaticLibrary (path.join (build_dir, 'expat'), source_list)

env.NoClean (lib)
