# 	Cairo 1.12.16 for Windows
#
#	author: "Finnian Reilly"
#	copyright: "Copyright (c) 2001-2010 Finnian Reilly"
#	contact: "finnian at eiffel hyphen loop dot com"
#	license: "MIT license (See: en.wikipedia.org/wiki/MIT_License)"
#	date: "7 Jan 2010"
#	revision: "0.1"

import os, sys, platform

from os import path

from eiffel_loop import platform

from eiffel_loop.scons import util
from eiffel_loop.eiffel import project

from eiffel_loop.scons import package
from eiffel_loop.scons import c

#Import ('env')

env = Environment (
	ENV = os.environ, # this is needed to reproduce the environment for external commands like LIB
	EIFFEL_LOOP = os.environ ['EIFFEL_LOOP'], ISE_PLATFORM = os.environ ['ISE_PLATFORM']
)


if platform.is_unix ():
	build_dir =  project.platform_spec_build_dir ()
	VariantDir (build_dir, 'source', duplicate=0)

	env ['BUILDERS']['C_library'] = Builder (
		action = c_library.get, suffix='.a', src_suffix='.getlib', emitter = util.complete_targets
	)
	lib := env.C_library (path.join (build_dir, 'libtag.a'), File (path.join (build_dir, 'taglib.getlib')))
	
	env.NoClean (lib)
#	Return (['downloaded_DLLs', 'dll_import_libs'])
	






