#	author: "Finnian Reilly"
#	copyright: "Copyright (c) 2001-2026 Finnian Reilly"
#	contact: "finnian at eiffel hyphen loop dot com"
#	license: "MIT license (See: en.wikipedia.org/wiki/MIT_License)"
#	date: "17 May 2026"
#	revision: "1.0"

import os
from eiffel_loop.os import path
from eiffel_loop.C_util import C_dev as C
from eiffel_loop.scons import c

# defines are need for inclusion of cecil.h via C_library/include/c_to_eiffel.h

if os.name == "nt":
	# Note UNICODE also has underscore variant
	defines = C.define_list ("_CRT_SECURE_NO_DEPRECATE _UNICODE _WIN32_WINNT=0x0500 EIF_THREADS UNICODE WINVER=0x0500")
	compiler_flags = ['-Ox', '-Zi', '-MT', '-w', '-nologo'] + defines
else:
	defines = C.define_list ("_GNU_SOURCE EIF_THREADS EIF_LINUXTHREADS ISE_GC")
	flags = C.flag_list (
		"expensive-optimizations merge-all-constants no-branch-count-reg omit-frame-pointer peephole unroll-loops"
	)
	compiler_flags = ['-g', '-c', '-w', '-O3', '-Wno-write-strings'] + flags + defines

vtd_xml_dir = path.expanded ('$C_VTD_XML')

include_path = [
	path.expanded ('$ISE_EIFFEL/studio/spec/$ISE_PLATFORM/include'),
	path.expanded ('$EIFFEL_LOOP/C_library/include'),
	path.join (vtd_xml_dir, 'include')
]

build_dir = path.expanded ('spec/$ISE_PLATFORM')
VariantDir (build_dir, 'source', duplicate=0)

library_path = path.join (build_dir, 'vtd-xml')

print ('Include paths:')
for i_path in include_path:
	print(i_path)

env = Environment (CCFLAGS = compiler_flags, CPPPATH = include_path, ENV = os.environ)

# Abbreviate long paths in compiler output
c.COMMAND_STRINGS ('C_VTD_XML EIFFEL_LOOP ISE_EIFFEL').configure (env)

Export ("env")

input_files = [path.join (build_dir, 'vtd2eiffel.c')] + SConscript (path.join (vtd_xml_dir, 'SConscript'))

lib = env.StaticLibrary (library_path, input_files)
print (lib)

env.NoClean (lib)
