#	author: "Finnian Reilly"
#	copyright: "Copyright (c) 2001-2010 Finnian Reilly"
#	contact: "finnian at eiffel hyphen loop dot com"
#	license: "MIT license (See: en.wikipedia.org/wiki/MIT_License)"
#	date: "21 May 2026"
#	revision: "0.2"

import os

from eiffel_loop.os import path
from eiffel_loop.eiffel import ise_environ
from eiffel_loop.C_util import C_dev as C
from eiffel_loop.scons import c

global ise
ise = ise_environ.shared

if os.name == "posix":
	raise NotImplementedError (
		"network-adapter.lib needed only for Windows implementation of\nEL_NETWORK_DEVICE_IMP and EL_NETWORK_DEVICE_LIST_IMP"
	)

# Note UNICODE also has underscore variant
defines = C.define_list ("_CRT_SECURE_NO_DEPRECATE _UNICODE _WIN32_WINNT=0x0500 EIF_THREADS UNICODE WINVER=0x0500 ")
compiler_flags = ['-Ox', '-Zi', '-MT', '-w', '-nologo'] + defines

include_path = [
	path.expanded ('$ISE_EIFFEL/studio/spec/$ISE_PLATFORM/include'), 'source'
]
	
env = Environment (CCFLAGS = compiler_flags, CPPPATH = include_path, ENV = os.environ)

# Abbreviate long paths in compiler output
c.COMMAND_STRINGS ('C_NET_ADAPTOR').configure (env)

build_dir = ise.spec_build_dir ()

VariantDir (build_dir, 'source', duplicate=0)

library_path = path.join (build_dir, 'network-adapter')

source_list = Glob (path.join (build_dir, '*.c'))

lib = env.StaticLibrary (library_path, source_list)

env.NoClean (lib)
