note
	description: "[
		Finalized executable tests for library [./library/app-manage.html app-manage.ecf]
	]"
	notes: "[
		Command option: `-app_manage_autotest'
		
		**Test Sets**
		
			${COMMAND_ARGUMENTS_TEST_SET}
	]"

	author: "Finnian Reilly"
	copyright: "Copyright (c) 2001-2022 Finnian Reilly"
	contact: "finnian at eiffel hyphen loop dot com"

	license: "MIT license (See: en.wikipedia.org/wiki/MIT_License)"
	date: "2025-11-17 16:00:41 GMT (Monday 17th November 2025)"
	revision: "2"

class
	APP_MANAGE_AUTOTEST_APP

inherit
	EL_AUTOTEST_APPLICATION [COMMAND_ARGUMENTS_TEST_SET]

create
	make

feature {NONE} -- Implementation

	compile: TUPLE [
		EL_ACTIVE_SERVICE_SCREEN,
		EL_COMMAND_SHELL_APPLICATION [EL_APPLICATION_COMMAND_SHELL],
		EL_DEBIAN_CONSTANTS, EL_DEBIAN_CONTROL, EL_DEBIAN_MAKE_SCRIPT, EL_DEBIAN_PACKAGER_APP,
		EL_DEBIAN_PACKAGER_I, EL_DEBIAN_PACKAGER_IMP,
		EL_DEFAULT_SOFTWARE_UPDATE_INFO,
		EL_DOWNLOADEABLE_RESOURCE,
		EL_LOCALIZED_DEBIAN_PACKAGER_APP,
		EL_MAKEABLE_FROM_ZSTRING_OPERAND_SETTER,
		EL_QUERY_SELF_APP,
		EL_RELECTIVE_XML_APP_CONFIGURATION,
		EL_RESOURCE_INSTALL_MANAGER,
		EL_RESOURCE_URL,
		EL_SERVICE_CONFIGURATION,
		EL_SERVICE_MANAGER_APP,
		EL_SERVICE_MANAGER_SHELL,
		EL_SERVICE_SCREEN,
		EL_SERVICE_SCREEN_LIST,
		EL_SOFTWARE_UPDATE_INFO,
		EL_STANDARD_INSTALLER_APP,
		EL_UNIX_APPLICATION,
		EL_UPDATEABLE_RESOURCE_SET,
		EL_VERSION_PATH_LIST,
		EL_XDG_DESKTOP
	]
		do
			create Result
		end
end