note
	description: "Finalized executable test sets"
	notes: "[
		Command option: `-rbox_autotest'
		
		**Test Sets**
		
			${ADD_ALBUM_ART_TASK_TEST_SET}
			${COLLATE_SONGS_TASK_TEST_SET}
			${EXPORT_MUSIC_TO_DEVICE_TASK_TEST_SET}
			${EXPORT_PLAYLISTS_TO_DEVICE_TASK_TEST_SET}
			${IMPORT_M3U_PLAYLISTS_TASK_TEST_SET}
			${IMPORT_NEW_MP3_TASK_TEST_SET}
			${IMPORT_VIDEOS_TASK_TEST_SET}
			${PUBLISH_DJ_EVENTS_TASK_TEST_TASK}
			${REPLACE_CORTINA_SET_TASK_TEST_SET}
			${REPLACE_SONGS_TASK_TEST_SET}
			${TANGO_MP3_FILE_COLLATOR_TEST_SET}
			${UPDATE_DJ_PLAYLISTS_TASK_TEST_SET}
	]"

	author: "Finnian Reilly"
	copyright: "Copyright (c) 2001-2022 Finnian Reilly"
	contact: "finnian at eiffel hyphen loop dot com"

	license: "MIT license (See: en.wikipedia.org/wiki/MIT_License)"
	date: "2024-01-20 19:18:24 GMT (Saturday 20th January 2024)"
	revision: "26"

class
	AUTOTEST_APP

inherit
	EL_CRC_32_AUTOTEST_APPLICATION [
		ADD_ALBUM_ART_TASK_TEST_SET,
		COLLATE_SONGS_TASK_TEST_SET,
		DISPLAY_MUSIC_BRAINZ_INFO_TASK_TEST_SET,
		EXPORT_MUSIC_TO_DEVICE_TASK_TEST_SET,
		EXPORT_PLAYLISTS_TO_DEVICE_TASK_TEST_SET,
		IMPORT_M3U_PLAYLISTS_TASK_TEST_SET,
		IMPORT_NEW_MP3_TASK_TEST_SET,
		IMPORT_VIDEOS_TASK_TEST_SET,
		PUBLISH_DJ_EVENTS_TASK_TEST_TASK,
		REPLACE_CORTINA_SET_TASK_TEST_SET,
		REPLACE_SONGS_TASK_TEST_SET,
		TANGO_MP3_FILE_COLLATOR_TEST_SET,
		UPDATE_DJ_PLAYLISTS_TASK_TEST_SET
	]
		redefine
			visible_types
		end

create
	make

feature {NONE} -- Implementation

	visible_types: TUPLE [
		EL_GVFS_COPY_COMMAND,
		EL_GVFS_FILE_EXISTS_COMMAND,
		EL_GVFS_MAKE_DIRECTORY_COMMAND,
		EL_GVFS_MOVE_COMMAND,
		DISPLAY_MUSIC_BRAINZ_INFO_TASK
	]
		do
			create Result
		end

end