note
	description: "[
		Finalized executable tests for Paypal Stand Button Manager library [./library/paypal-SBM.html paypal-SBM.ecf]
	]"
	notes: "[
		Command option: `-paypal_standard_button_manager_autotest'
		
		**Test Sets**
		
			${PAYPAL_TEST_SET}
	]"

	author: "Finnian Reilly"
	copyright: "Copyright (c) 2001-2022 Finnian Reilly"
	contact: "finnian at eiffel hyphen loop dot com"

	license: "MIT license (See: en.wikipedia.org/wiki/MIT_License)"
	date: "2025-05-15 9:08:15 GMT (Thursday 15th May 2025)"
	revision: "70"

class
	PAYPAL_STANDARD_BUTTON_MANAGER_AUTOTEST_APP

inherit
	EL_AUTOTEST_APPLICATION [PAYPAL_TEST_SET]

create
	make

feature {NONE} -- Implementation

	compile: TUPLE [
		PP_API_VERSION,

		PP_BUTTON_PARAMETER,
		PP_BUTTON_DETAIL,
		PP_BUTTON_DETAILS_QUERY_RESULTS,
		PP_BUTTON_LOCALE,
		PP_BUTTON_META_DATA,
		PP_BUTTON_METHOD [PP_HTTP_RESPONSE],
		PP_BUTTON_OPTION,
		PP_BUTTON_SEARCH_METHOD,
		PP_BUTTON_SEARCH_RESULTS,
		PP_BUTTON_SUB_PARAMETER_LIST,
		PP_BUY_OPTIONS,

		PP_CONFIGURATION,
		PP_CREATE_BUTTON_METHOD,
		PP_CREDENTIALS,

		PP_DATE_TIME_RANGE,
		PP_GET_BUTTON_DETAILS_METHOD,
		PP_HTTP_CONNECTION,
		PP_MANAGE_BUTTON_STATUS_METHOD,

		PP_NAME_TRANSLATER,
		PP_NUMBERED_VARIABLE_NAME_SEQUENCE,
		PP_NUMBERED_VARIABLE_PARAMETER_LIST,
		PP_NVP_API_CONNECTION,

		PP_OPTION_PRICE_PARAMETER_LIST,
		PP_OPTION_SELECT_SUB_PARAMETER_LIST,
		PP_PRODUCT_INFO,
		PP_REFLECTIVELY_SETTABLE_LIST [PP_SETTABLE_FROM_UPPER_CAMEL_CASE],
		PP_SHARED_API_CONNECTION,
		PP_SHARED_CONFIGURATION,
		PP_SUB_PARAMETER_LIST,
		PP_TEST_COMMAND_SHELL,
		PP_UPDATE_BUTTON_METHOD,
		PP_VARIABLE_NAME_SEQUENCE
	]
		do
			create Result
		end

end